#include <bits/stdc++.h>

const int MAXN = 2010;

using ll = long long;

int n = 10;

int main() {

    std::puts("RDRUDRLLRLLRUURLLRDDRDDRLLRRDRRDRLLRRLRRRRLLRDDRDDRLLRUURUURUURUURUURUURUURUURUURIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP");

}
